### ISSUE TITLE
Spec not passing due to file format on save

### ISSUE THREAD

**Issue by joshuaneedham** [learn-co-students/css-kitten-wheelbarrow-lab-v-000#31]
Using VS Code and the Beautify extension is removing the space on save and the following test won't pass. 
```rspec
it 'selects the image based on the respective sibling element' do
    expect(css_file_contents).to include('#ball + img')
  end
```
I had to remove the space for the test to pass as it saves the CSS as shown below.
```css
#ball+img {
  position: absolute;
  z-index: 4;
  top: 260px;
  left: 455px;
}
```
